version: '3.8'

# Docker Compose pour test local
# Pour ssdv2, utilisez le fichier qbittorrent-monitor.yml

services:
  qbittorrent-monitor:
    build: .
    container_name: qbittorrent-error-monitor
    restart: unless-stopped
    
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=Europe/Paris
    
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      # Adaptez ce chemin selon votre environnement
      - ${HOME}/.config:/configs:ro
    
    networks:
      - default
    
    mem_limit: 128m
    cpus: 0.25

networks:
  default:
    driver: bridge
