#!/usr/bin/bash

# Handle PUID/PGID for LinuxServer compatibility
PUID=${PUID:-911}
PGID=${PGID:-911}

echo "**** Setting up user permissions ****"

# Change abc user/group to desired PUID/PGID
groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo "**** User abc set to PUID=$PUID and PGID=$PGID ****"
