# Configuration QBittorrent Monitor
# Auto-configuration pour environnement Docker

# Configuration générale
monitor:
  check_interval: 300  # 5 minutes
  log_level: "INFO"
  dry_run: false
  timezone: "Europe/Paris"

# Configuration Docker
docker:
  network: "bridge"  # Réseau par défaut Docker
  socket_path: "/var/run/docker.sock"

# Configuration des services
services:
  sonarr:
    enabled: true
    port: 8989
    api_version: "v3"
    container_names: 
      - "sonarr"
    config_paths:
      - "/configs/sonarr/config"  # Chemin monté dans le conteneur
    search_command: "missingEpisodeSearch"
    
  radarr:
    enabled: true
    port: 7878
    api_version: "v3"
    container_names:
      - "radarr"
    config_paths:
      - "/configs/radarr/config"  # Chemin monté dans le conteneur
    search_command: "MissingMoviesSearch"

# Patterns d'erreurs qBittorrent à détecter
error_patterns:
  - "qBittorrent is reporting an error"
  - "qBittorrent has returned an error"
  - "Connection to qBittorrent failed"
  - "qbittorrent error"
  - "torrent client error"

# Configuration des logs
logging:
  file_path: "/config/logs/qbittorrent-monitor.log"
  max_size_mb: 50
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Configuration de sécurité
security:
  validate_paths: true
  sanitize_inputs: true
  max_path_length: 4096
  allowed_user_chars: "a-zA-Z0-9._-"

# Métriques et monitoring
monitoring:
  enable_stats: true
  stats_interval: 600  # Sauvegarde stats toutes les 10min
  enable_health_check: true
  health_check_port: 8080
