# Configuration QBittorrent Error Monitor
qbittorrent:
  host: "localhost"
  port: 8080
  username: "admin"
  password: "adminadmin"
  use_https: false

applications:
  sonarr:
    enabled: true
    url: "http://localhost:8989"
    api_key: "your_sonarr_api_key"
  radarr:
    enabled: true
    url: "http://localhost:7878"
    api_key: "your_radarr_api_key"

monitoring:
  check_interval: 300           # Intervalle en secondes (5 minutes)
  max_retries: 3
  
error_patterns:
  connection_errors:
    - "Connection timed out"
    - "No such host is known"
    - "Name resolution failed"
    - "Connection refused"
  
  tracker_errors:
    - "Tracker error"
    - "Announce failed"
    - "Unregistered torrent"
    - "Tracker offline"
  
  file_errors:
    - "No space left on device"
    - "Permission denied"
    - "Disk full"
    - "Input/output error"

logging:
  level: "INFO"                 # DEBUG|INFO|WARNING|ERROR
  file: "logs/monitor.log"
  max_size_mb: 10
  backup_count: 5
