# Configuration QBittorrent Monitor pour ssdv2
# Auto-configuration activée pour déploiement simple

# Configuration générale
monitor:
  check_interval: 300  # 5 minutes
  log_level: "INFO"
  dry_run: false
  timezone: "Europe/Paris"

# Configuration qBittorrent (auto-détection)
qbittorrent:
  auto_detect: true
  container_names:
    - "qbittorrent"
    - "qbittorrent-vpn"
  web_ui:
    host: "localhost"
    port: 8080
    username: "admin"
    # password: auto-détecté

# Configuration Sonarr (auto-détection)
sonarr:
  enabled: true
  auto_detect: true
  container_names:
    - "sonarr"
  config_paths:
    - "/configs/sonarr/config"
  api:
    auto_detect_key: true

# Configuration Radarr (auto-détection)
radarr:
  enabled: true
  auto_detect: true
  container_names:
    - "radarr"
  config_paths:
    - "/configs/radarr/config"
  api:
    auto_detect_key: true

# Configuration Docker
docker:
  network: "traefik_proxy"  # Réseau par défaut ssdv2
  socket_path: "/var/run/docker.sock"

# Logging
logging:
  file_path: "/app/logs/qbittorrent-monitor.log"
  max_size_mb: 50
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Actions
actions:
  restart_containers: true
  notify_errors: true
  statistics: true
  max_file_size: "10MB"
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Configuration de sécurité
security:
  validate_paths: true
  sanitize_inputs: true
  max_path_length: 4096
  allowed_user_chars: "a-zA-Z0-9._-"

# Métriques et monitoring
monitoring:
  enable_stats: true
  stats_interval: 600  # Sauvegarde stats toutes les 10min
  enable_health_check: true
  health_check_port: 8080
