#!/command/with-contenv bash

# Créer le répertoire de configuration s'il n'existe pas
if [ ! -d "/config" ]; then
    mkdir -p /config
fi

# Copier la configuration par défaut si elle n'existe pas
if [ ! -f "/config/config.yaml" ]; then
    cp /defaults/config.yaml /config/
fi

# Créer le répertoire de logs
mkdir -p /config/logs

# S'assurer que les permissions sont correctes
lsiown abc:abc /config
